name: AsyncScoreBoard
main: asyncscoreboard.Main
version: 1.2
authors: 
- _Shevchik_
depend: [PlaceholderAPI]
softdepend: [WorldGuard, Vault]
commands:
  asb:
    description: All AsyncScoreBoard commands
