name: AsyncScoreBoard
main: asyncscoreboard.Main
version: 1.1
authors: 
- _Shevchik_
depend: [PlaceholderAPI]
softdepend: [WorldGuard]
commands:
  asb:
    description: All AsyncScoreBoard commands
