name: AsyncScoreBoard
main: asyncscoreboard.Main
api-version: 1.13
version: 1.4
authors: 
- _Shevchik_
depend: [PlaceholderAPI]
softdepend: [WorldGuard, Vault]
commands:
  asb:
    description: All AsyncScoreBoard commands
